lib/docu_sign_web/router.ex
defmodule DocuSignWeb.Router do
  use DocuSignWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DocuSignWeb do
    pipe_through [:browser, DocuSignWeb.Plugs.Guest]

    resources "/register", UserController, only: [:create, :new, :index, :show]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  scope "/", DocuSignWeb do
    pipe_through [:browser, DocuSignWeb.Plugs.Auth]

    get "/logout", SessionController, :delete

    get "/", PageController, :index
    get "/show", PageController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", DocuSignWeb do
  #   pipe_through :api
  # end
end

lib/docu_sign_web/controllers/session_controller.ex
defmodule DocuSignWeb.SessionController do
  use DocuSignWeb, :controller

  alias DocuSign.Accounts.Auth
  alias DocuSign.Repo

  def new(conn, _params) do
    render(conn, "new.html")
  end

  @spec create(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def create(conn, %{"session" => auth_params}) do
    case Auth.login(auth_params, Repo) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "Signed in successfully.")
        |> redirect(to: Routes.page_path(conn, :show))
      :error ->
        conn
        |> put_flash(:error, "There was a problem with your username/password")
        |> render("new.html")
    end
  end

  def delete(conn, _params) do
    conn
    |> delete_session(:current_user_id)
    |> put_flash(:info, "signed out successfully.")
    |> redirect(to: Routes.session_path(conn, :new))
  end
end

lib/docu_sign_web/views/session_view.ex
defmodule DocuSignWeb.SessionView do
  use DocuSignWeb, :view

end

lib/docu_sign_web/templates/session/new.html.eex
<div class= "row form_container">
    <div class="col s12 m6 offset-m3">
        <div class="card">
            <div class= "card-content">
                <p>Login</p>
                    <div class="row card-form">
                    <%= form_for @conn, Routes.session_path(@conn, :new), [as: :session], fn f-> %>
                    <%= text_input f, :username, placeholder: "Username" %>
                    <%= password_input f, :password, placeholder: "Password" %>
                    <%= submit "Submit", class: "btn secondary-color" %>
                </div>
                <p> You dont have an account yet? </p>
                    <%= link "Create an Account", to: Routes.user_path(@conn, :new), class: "btn secondary-color" %>
                <% end %>
                
            </div>
        </div>
    </div>
</div>