lib/docu_sign_web/router.ex
defmodule DocuSignWeb.Router do
  use DocuSignWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DocuSignWeb do
    pipe_through [:browser, DocuSignWeb.Plugs.Guest]

    resources "/register", UserController, only: [:create, :new, :index, :show]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  scope "/", DocuSignWeb do
    pipe_through [:browser, DocuSignWeb.Plugs.Auth]

    get "/logout", SessionController, :delete

    get "/", PageController, :index
    get "/show", PageController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", DocuSignWeb do
  #   pipe_through :api
  # end
end

lib/docu_sign/accounts/user.ex
defmodule DocuSign.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias DocuSign.Accounts.Encryption

  schema "users" do
    field :email, :string
    field :encrypted_password, :string
    field :username, :string

    # virtual fields
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:username, :email, :password])
    |> validate_required([:username, :email])
    |> validate_length(:password, min: 6)
    |> validate_confirmation(:password)
    |> validate_format(:username, ~r/^[a-z0-9][a-z0-9]+[a-z0-9]$/i)
    |> validate_length(:username, min: 3)
    |> unique_constraint(:username)
    |> unique_constraint(:email)
    |> downcase_username
    |> encrypt_password
  end

  defp encrypt_password(changeset) do
    password = get_change(changeset, :password)
    if password do
      encrypted_password = Encryption.hash_password(password)
      put_change(changeset, :encrypted_password, encrypted_password)
    else
      changeset
    end
  end

  defp downcase_username(changeset) do
    update_change(changeset, :username, &String.downcase/1)
  end
end

lib/docu_sign_web/controllers/user_controller.ex
defmodule DocuSignWeb.UserController do
  use DocuSignWeb, :controller

  alias DocuSign.Accounts
  alias DocuSign.Accounts.User

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end
end

lib/docu_sign_web/views/user_view.ex
defmodule DocuSignWeb.UserView do
  use DocuSignWeb, :view
end

lib/docu_sign_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/docu_sign_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= text_input f, :username %>
  <%= error_tag f, :username %>

  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <%= password_input f, :password, placeholder: "Password" %>
  <%= error_tag f, :password %>

  <%= password_input f, :password_confirmation, placeholder: "Confirm Password" %>
  <%= error_tag f, :password_confirmation %>

  <div>
    <%= submit "Submit", class: "btn right secondary-color" %>
  </div>
<% end %>

lib/docu_sign_web/templates/user/index.html.eex
<h1>Welcome to Docu Sign</h1>

<p> Do you have an account? </p>

<p><%= link "Log in", to: Routes.session_path(@conn, :new) %></p>

<p> You dont? Register to access Docu Sign </p>

<p><%= link "Register", to: Routes.user_path(@conn, :new) %></p>

lib/docu_sign_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/docu_sign_web/templates/user/show.html.eex
<h1>Show User</h1>

<ul>

  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Encrypted password:</strong>
    <%= @user.encrypted_password %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>